<template>
  <div>
    <Table :tableList="tableList" v-bind="tableConfig">
      <template #menuType="scope">
        <el-tag v-if="scope.row.type == 0" type="primary">目录</el-tag>
        <el-tag v-if="scope.row.type == 1" type="success">菜单</el-tag>
        <el-tag v-if="scope.row.type == 2" type="danger">按钮</el-tag>
      </template>
      <template #action>
        <div style="padding: 5px 0">
          <el-button size="default" icon="EditPen" type="primary"
            >编辑</el-button
          >
          <el-button size="default" icon="Delete" type="danger">删除</el-button>
        </div>
      </template>
    </Table>
  </div>
</template>

<script setup lang="ts">
import { tableConfig } from './config/table-config'
import Table from '@/components/tables/Table.vue'
import { ref } from 'vue'

const tableList = ref([
  {
    menuId: 3,
    parentId: 0,
    menuLabel: '系统管理',
    menuCode: 'sys:system',
    name: '',
    path: '/system',
    url: '',
    type: '0',
    icon: 'el-icon-menu',
    remark: '',
    parentName: '顶级菜单',
    orderNum: 1,
    children: [
      {
        menuId: 4,
        parentId: 3,
        menuLabel: '员工管理',
        menuCode: 'sys:sysUserList',
        name: 'sys:user:index',
        path: '/sysUserList',
        url: '/system/sysUserList',
        type: '1',
        icon: 'el-icon-s-custom',
        remark: '',
        parentName: '系统管理',
        orderNum: 1,
        children: [
          {
            menuId: 7,
            parentId: 4,
            menuLabel: '新增',
            menuCode: 'sys:user:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '员工管理',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 8,
            parentId: 4,
            menuLabel: '编辑',
            menuCode: 'sys:user:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '员工管理',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 9,
            parentId: 4,
            menuLabel: '删除',
            menuCode: 'sys:user:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '员工管理',
            orderNum: 3,
            children: [],
            open: null
          },
          {
            menuId: 77,
            parentId: 4,
            menuLabel: '分配角色',
            menuCode: 'sys:user:assignRole',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '员工管理',
            orderNum: 5,
            children: [],
            open: null
          }
        ],
        open: null
      },
      {
        menuId: 5,
        parentId: 3,
        menuLabel: '角色管理',
        menuCode: 'sys:sysRoleList',
        name: 'sysRoleList',
        path: '/sysRoleList',
        url: '/system/sysRoleList',
        type: '1',
        icon: 'el-icon-date',
        remark: '',
        parentName: '系统管理',
        orderNum: 2,
        children: [
          {
            menuId: 10,
            parentId: 5,
            menuLabel: '新增',
            menuCode: 'sys:role:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '角色管理',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 11,
            parentId: 5,
            menuLabel: '编辑',
            menuCode: 'sys:role:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '角色管理',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 12,
            parentId: 5,
            menuLabel: '删除',
            menuCode: 'sys:role:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '角色管理',
            orderNum: 3,
            children: [],
            open: null
          },
          {
            menuId: 78,
            parentId: 5,
            menuLabel: '分配权限',
            menuCode: 'sys:role:assignMenu',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '角色管理',
            orderNum: 4,
            children: [],
            open: null
          }
        ],
        open: null
      },
      {
        menuId: 6,
        parentId: 3,
        menuLabel: '权限管理',
        menuCode: 'sys:sysMenuList',
        name: 'sysMenuList',
        path: '/sysMenuList',
        url: '/system/sysMenuList',
        type: '1',
        icon: 'el-icon-school',
        remark: '',
        parentName: '系统管理',
        orderNum: 3,
        children: [
          {
            menuId: 13,
            parentId: 6,
            menuLabel: '新增',
            menuCode: 'sys:menu:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '权限管理',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 14,
            parentId: 6,
            menuLabel: '编辑',
            menuCode: 'sys:menu:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '权限管理',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 15,
            parentId: 6,
            menuLabel: '删除',
            menuCode: 'sys:menu:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '权限管理',
            orderNum: 3,
            children: [],
            open: null
          }
        ],
        open: null
      }
    ],
    open: null
  },
  {
    menuId: 16,
    parentId: 0,
    menuLabel: '房屋管理',
    menuCode: 'sys:home:index',
    name: '',
    path: '/sysHouse',
    url: '',
    type: '0',
    icon: 'el-icon-s-help',
    remark: '',
    parentName: '顶级菜单',
    orderNum: 2,
    children: [
      {
        menuId: 22,
        parentId: 16,
        menuLabel: '栋数管理',
        menuCode: 'sys:houseBuilding',
        name: 'houseBuilding',
        path: '/houseBuilding',
        url: '/house/houseBuilding',
        type: '1',
        icon: 'table',
        remark: '',
        parentName: '房屋管理',
        orderNum: 1,
        children: [
          {
            menuId: 23,
            parentId: 22,
            menuLabel: '新增',
            menuCode: 'sys:houseBuilding:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '栋数管理',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 24,
            parentId: 22,
            menuLabel: '编辑',
            menuCode: 'sys:houseBuilding:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '栋数管理',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 25,
            parentId: 22,
            menuLabel: '删除',
            menuCode: 'sys:houseBuilding:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '栋数管理',
            orderNum: 3,
            children: [],
            open: null
          }
        ],
        open: null
      },
      {
        menuId: 21,
        parentId: 16,
        menuLabel: '单元管理',
        menuCode: 'sys:houseUnit',
        name: 'houseUnit',
        path: '/houseUnit',
        url: '/house/houseUnit',
        type: '1',
        icon: 'table',
        remark: '',
        parentName: '房屋管理',
        orderNum: 2,
        children: [
          {
            menuId: 26,
            parentId: 21,
            menuLabel: '新增',
            menuCode: 'sys:houseUnit:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '单元管理',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 27,
            parentId: 21,
            menuLabel: '编辑',
            menuCode: 'sys:houseUnit:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '单元管理',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 28,
            parentId: 21,
            menuLabel: '删除',
            menuCode: 'sys:houseUnit:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '单元管理',
            orderNum: 3,
            children: [],
            open: null
          }
        ],
        open: null
      },
      {
        menuId: 17,
        parentId: 16,
        menuLabel: '房屋列表',
        menuCode: 'sys:house:list',
        name: 'sysHouseList',
        path: '/sysHouseList',
        url: '/house/houseList',
        type: '1',
        icon: 'el-icon-mobile',
        remark: '',
        parentName: '房屋管理',
        orderNum: 3,
        children: [
          {
            menuId: 18,
            parentId: 17,
            menuLabel: '新增',
            menuCode: 'sys:house:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '房屋列表',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 19,
            parentId: 17,
            menuLabel: '编辑',
            menuCode: 'sys:house:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '房屋列表',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 20,
            parentId: 17,
            menuLabel: '删除',
            menuCode: 'sys:house:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '房屋列表',
            orderNum: 3,
            children: [],
            open: null
          }
        ],
        open: null
      }
    ],
    open: null
  },
  {
    menuId: 29,
    parentId: 0,
    menuLabel: '车位管理',
    menuCode: 'sys:sysPark',
    name: '',
    path: '/sysPark',
    url: '',
    type: '0',
    icon: 'el-icon-money',
    remark: '',
    parentName: '顶级菜单',
    orderNum: 3,
    children: [
      {
        menuId: 30,
        parentId: 29,
        menuLabel: '车位管理',
        menuCode: 'sys:parkList',
        name: 'parkList',
        path: '/parkList',
        url: '/park/parkList',
        type: '1',
        icon: 'el-icon-money',
        remark: '',
        parentName: '车位管理',
        orderNum: 1,
        children: [
          {
            menuId: 31,
            parentId: 30,
            menuLabel: '新增',
            menuCode: 'sys:parkList:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '车位管理',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 32,
            parentId: 30,
            menuLabel: '编辑',
            menuCode: 'sys:parkList:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '车位管理',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 33,
            parentId: 30,
            menuLabel: '删除',
            menuCode: 'sys:parkList:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '车位管理',
            orderNum: 3,
            children: [],
            open: null
          }
        ],
        open: null
      }
    ],
    open: null
  },
  {
    menuId: 34,
    parentId: 0,
    menuLabel: '业主管理',
    menuCode: 'sys:live',
    name: '',
    path: '/live',
    url: '',
    type: '0',
    icon: 'el-icon-s-grid',
    remark: '',
    parentName: '顶级菜单',
    orderNum: 4,
    children: [
      {
        menuId: 35,
        parentId: 34,
        menuLabel: '业主列表',
        menuCode: 'sys:liveUser',
        name: 'liveUser',
        path: '/liveUser',
        url: '/live/liveUser',
        type: '1',
        icon: 'el-icon-s-data',
        remark: '',
        parentName: '业主管理',
        orderNum: 1,
        children: [
          {
            menuId: 36,
            parentId: 35,
            menuLabel: '新增',
            menuCode: 'sys:liveUser:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '业主列表',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 37,
            parentId: 35,
            menuLabel: '编辑',
            menuCode: 'sys:liveUser:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '业主列表',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 38,
            parentId: 35,
            menuLabel: '删除',
            menuCode: 'sys:liveUser:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '业主列表',
            orderNum: 3,
            children: [],
            open: null
          },
          {
            menuId: 39,
            parentId: 35,
            menuLabel: '分配房屋',
            menuCode: 'sys:liveUser:assignHome',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '业主列表',
            orderNum: 4,
            children: [],
            open: null
          },
          {
            menuId: 40,
            parentId: 35,
            menuLabel: '分配车位',
            menuCode: 'sys:liveUser:assignCar',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '业主列表',
            orderNum: 6,
            children: [],
            open: null
          },
          {
            menuId: 41,
            parentId: 35,
            menuLabel: '退房',
            menuCode: 'sys:liveUser:returnHome',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '业主列表',
            orderNum: 7,
            children: [],
            open: null
          },
          {
            menuId: 42,
            parentId: 35,
            menuLabel: '退车位',
            menuCode: 'sys:liveUser:returnCar',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '业主列表',
            orderNum: 8,
            children: [],
            open: null
          }
        ],
        open: null
      }
    ],
    open: null
  },
  {
    menuId: 43,
    parentId: 0,
    menuLabel: '收费管理',
    menuCode: 'sys:fee',
    name: '',
    path: '/fee',
    url: '',
    type: '0',
    icon: 'el-icon-s-open',
    remark: '',
    parentName: '顶级菜单',
    orderNum: 5,
    children: [
      {
        menuId: 44,
        parentId: 43,
        menuLabel: '电费管理',
        menuCode: 'sys:feePower',
        name: 'feePower',
        path: '/feePower',
        url: '/fee/feePower',
        type: '1',
        icon: 'el-icon-picture',
        remark: '',
        parentName: '收费管理',
        orderNum: 1,
        children: [
          {
            menuId: 47,
            parentId: 44,
            menuLabel: '新增',
            menuCode: 'sys:feePower:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '电费管理',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 48,
            parentId: 44,
            menuLabel: '编辑',
            menuCode: 'sys:feePower:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '电费管理',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 49,
            parentId: 44,
            menuLabel: '删除',
            menuCode: 'sys:feePower:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '电费管理',
            orderNum: 3,
            children: [],
            open: null
          },
          {
            menuId: 81,
            parentId: 44,
            menuLabel: '缴费',
            menuCode: 'sys:feePower:pay',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '电费管理',
            orderNum: 4,
            children: [],
            open: null
          }
        ],
        open: null
      },
      {
        menuId: 45,
        parentId: 43,
        menuLabel: '水费管理',
        menuCode: 'sys:feeWater',
        name: 'feeWater',
        path: '/feeWater',
        url: '/fee/feeWater',
        type: '1',
        icon: 'el-icon-s-data',
        remark: '',
        parentName: '收费管理',
        orderNum: 2,
        children: [
          {
            menuId: 50,
            parentId: 45,
            menuLabel: '新增',
            menuCode: 'sys:feeWater:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '水费管理',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 51,
            parentId: 45,
            menuLabel: '编辑',
            menuCode: 'sys:feeWater:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '水费管理',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 52,
            parentId: 45,
            menuLabel: '删除',
            menuCode: 'sys:feeWater:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '水费管理',
            orderNum: 3,
            children: [],
            open: null
          },
          {
            menuId: 83,
            parentId: 45,
            menuLabel: '缴费',
            menuCode: 'sys:feeWater:pay',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '水费管理',
            orderNum: 4,
            children: [],
            open: null
          }
        ],
        open: null
      },
      {
        menuId: 46,
        parentId: 43,
        menuLabel: '停车管理',
        menuCode: 'sys:feePark',
        name: 'feePark',
        path: '/feePark',
        url: '/fee/feePark',
        type: '1',
        icon: 'el-icon-s-order',
        remark: '',
        parentName: '收费管理',
        orderNum: 3,
        children: [
          {
            menuId: 53,
            parentId: 46,
            menuLabel: '新增',
            menuCode: 'sys:feePark:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '停车管理',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 54,
            parentId: 46,
            menuLabel: '编辑',
            menuCode: 'sys:feePark:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '停车管理',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 55,
            parentId: 46,
            menuLabel: '删除',
            menuCode: 'sys:feePark:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '停车管理',
            orderNum: 3,
            children: [],
            open: null
          },
          {
            menuId: 82,
            parentId: 46,
            menuLabel: '缴费',
            menuCode: 'sys:feePark:pay',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '停车管理',
            orderNum: 4,
            children: [],
            open: null
          }
        ],
        open: null
      }
    ],
    open: null
  },
  {
    menuId: 84,
    parentId: 0,
    menuLabel: '缴费记录',
    menuCode: 'sys:feeList',
    name: '',
    path: '/feeList',
    url: '',
    type: '0',
    icon: 'el-icon-c-scale-to-original',
    remark: '',
    parentName: '顶级菜单',
    orderNum: 6,
    children: [
      {
        menuId: 85,
        parentId: 84,
        menuLabel: '我的电费',
        menuCode: 'sys:myPowerFee',
        name: 'myPowerFee',
        path: '/myPowerFee',
        url: '/feeList/myPowerFee',
        type: '1',
        icon: 'el-icon-date',
        remark: '',
        parentName: '缴费记录',
        orderNum: 1,
        children: [],
        open: null
      },
      {
        menuId: 86,
        parentId: 84,
        menuLabel: '我的水费',
        menuCode: 'sys:myWaterFee',
        name: 'myWaterFee',
        path: '/myWaterFee',
        url: '/feeList/myWaterFee',
        type: '1',
        icon: 'el-icon-s-shop',
        remark: '',
        parentName: '缴费记录',
        orderNum: 2,
        children: [],
        open: null
      },
      {
        menuId: 87,
        parentId: 84,
        menuLabel: '我的停车费',
        menuCode: 'sys:myParkFee',
        name: 'myParkFee',
        path: '/myParkFee',
        url: '/feeList/myParkFee',
        type: '1',
        icon: 'el-icon-s-finance',
        remark: '',
        parentName: '缴费记录',
        orderNum: 3,
        children: [],
        open: null
      }
    ],
    open: null
  },
  {
    menuId: 56,
    parentId: 0,
    menuLabel: '投诉管理',
    menuCode: 'sys:userComplaint',
    name: '',
    path: '/userComplaint',
    url: '',
    type: '0',
    icon: 'el-icon-date',
    remark: '',
    parentName: '顶级菜单',
    orderNum: 6,
    children: [
      {
        menuId: 57,
        parentId: 56,
        menuLabel: '投诉列表',
        menuCode: 'sys:userComplaintList',
        name: 'userComplaintList',
        path: '/userComplaintList',
        url: '/userComplaint/userComplaint',
        type: '1',
        icon: 'el-icon-edit-outline',
        remark: '',
        parentName: '投诉管理',
        orderNum: 1,
        children: [
          {
            menuId: 80,
            parentId: 57,
            menuLabel: '处理',
            menuCode: 'sys:myUserComplaint:do',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '投诉列表',
            orderNum: 1,
            children: [],
            open: null
          }
        ],
        open: null
      },
      {
        menuId: 58,
        parentId: 56,
        menuLabel: '我的投诉',
        menuCode: 'sys:myUserComplaint',
        name: 'myUserComplaint',
        path: '/myUserComplaint',
        url: '/userComplaint/myUserComplaint',
        type: '1',
        icon: 'el-icon-menu',
        remark: '',
        parentName: '投诉管理',
        orderNum: 2,
        children: [
          {
            menuId: 62,
            parentId: 58,
            menuLabel: '新增',
            menuCode: 'sys:myUserComplaint:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '我的投诉',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 63,
            parentId: 58,
            menuLabel: '编辑',
            menuCode: 'sys:myUserComplaint:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '我的投诉',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 64,
            parentId: 58,
            menuLabel: '删除',
            menuCode: 'sys:myUserComplaint:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '我的投诉',
            orderNum: 3,
            children: [],
            open: null
          }
        ],
        open: null
      }
    ],
    open: null
  },
  {
    menuId: 65,
    parentId: 0,
    menuLabel: '维修管理',
    menuCode: 'sys:repairModel',
    name: '',
    path: '/repairModel',
    url: '',
    type: '0',
    icon: 'el-icon-picture-outline',
    remark: '',
    parentName: '顶级菜单',
    orderNum: 7,
    children: [
      {
        menuId: 66,
        parentId: 65,
        menuLabel: '维修列表',
        menuCode: 'sys:repairList',
        name: 'repairList',
        path: '/repairList',
        url: '/repair/repairList',
        type: '1',
        icon: 'el-icon-s-marketing',
        remark: '',
        parentName: '维修管理',
        orderNum: 1,
        children: [
          {
            menuId: 79,
            parentId: 66,
            menuLabel: '处理',
            menuCode: 'sys:repairList:do',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '维修列表',
            orderNum: 1,
            children: [],
            open: null
          }
        ],
        open: null
      },
      {
        menuId: 67,
        parentId: 65,
        menuLabel: '我的维修',
        menuCode: 'sys:myRepair',
        name: 'myRepair',
        path: '/myRepair',
        url: '/repair/myRepair',
        type: '1',
        icon: 'el-icon-picture-outline',
        remark: '',
        parentName: '维修管理',
        orderNum: 2,
        children: [
          {
            menuId: 68,
            parentId: 67,
            menuLabel: '新增',
            menuCode: 'sys:myRepair:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '我的维修',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 69,
            parentId: 67,
            menuLabel: '编辑',
            menuCode: 'sys:myRepair:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '我的维修',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 70,
            parentId: 67,
            menuLabel: '删除',
            menuCode: 'sys:myRepair:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '我的维修',
            orderNum: 3,
            children: [],
            open: null
          }
        ],
        open: null
      }
    ],
    open: null
  },
  {
    menuId: 71,
    parentId: 0,
    menuLabel: '公告管理',
    menuCode: 'sys:notice',
    name: '',
    path: '/notice',
    url: '',
    type: '0',
    icon: 'el-icon-document-copy',
    remark: '',
    parentName: '顶级菜单',
    orderNum: 8,
    children: [
      {
        menuId: 72,
        parentId: 71,
        menuLabel: '公告列表',
        menuCode: 'sys:noticeList',
        name: 'noticeList',
        path: '/noticeList',
        url: '/notice/noticeList',
        type: '1',
        icon: 'el-icon-s-marketing',
        remark: '',
        parentName: '公告管理',
        orderNum: 1,
        children: [
          {
            menuId: 73,
            parentId: 72,
            menuLabel: '新增',
            menuCode: 'sys:noticeList:add',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '公告列表',
            orderNum: 1,
            children: [],
            open: null
          },
          {
            menuId: 74,
            parentId: 72,
            menuLabel: '编辑',
            menuCode: 'sys:noticeList:edit',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '公告列表',
            orderNum: 2,
            children: [],
            open: null
          },
          {
            menuId: 75,
            parentId: 72,
            menuLabel: '删除',
            menuCode: 'sys:noticeList:delete',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '公告列表',
            orderNum: 3,
            children: [],
            open: null
          },
          {
            menuId: 76,
            parentId: 72,
            menuLabel: '查看',
            menuCode: 'sys:notice:look',
            name: '',
            path: '',
            url: '',
            type: '2',
            icon: '',
            remark: '',
            parentName: '公告列表',
            orderNum: 4,
            children: [],
            open: null
          }
        ],
        open: null
      }
    ],
    open: null
  }
])
</script>

<style scoped></style>
